### ISSUE TITLE
Question about fused FDG-PET/CT dataset

### ISSUE THREAD

**Issue by yrsunn** [lab-midas/TCIA_processing#2]
Hey, I have two questions:

- how could I get fused FDG-PET/CT whole-body data (as showed here https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=93258287) based on the available PET (SUVs) and CT_res files? Is there any formula to combine these two?
- Is there any information to let me know which patients are healthy, which are not?

Thanks for your time!

**Comment by thomaskuestner** [comment]
1. Most DICOM viewers let you create these kinds of images as overlay of PET or CT (in their respective color maps) with the masks. For example 3D Slicer or MITK can provide you this image. We have no code in this repository to create this image output.
2. Please refer to the "clinical data" csv file on TCIA: https://wiki.cancerimagingarchive.net/pages/viewpage.action?pageId=93258287
"NEGATIVE" refers to patients with no FDG-avid lesion uptake = "healthy" 
Please note that they are not actually healthy, as they had some primary indication to receive a PET/CT imaging.

**Comment by DanguiYang** [comment]
![微信截图_20240115225402](https://github.com/lab-midas/TCIA_processing/assets/125953252/92c02ecd-fba2-479a-8980-c15fa774ff79)
Hey, I have one questions:
Why is there no response and no output after I input according to the format conversion command?

**Comment by thomaskuestner** [comment]
`tcia_dicom_to_mha.py` seems to be a file which you created yourself?
We don't have this in the repository, hence I cannot tell you why this is not working. 
`python3 tcia_dicom_to_nifti.py F:/manifest-...../DICOM/FDG-PET-CT-Lesions/ F:/maniftest-..../NIFTI/FDG-PET-CT-Lesions/` should work

**Comment by DanguiYang** [comment]
> `tcia_dicom_to_mha.py` seems to be a file which you created yourself? We don't have this in the repository, hence I cannot tell you why this is not working. `python3 tcia_dicom_to_nifti.py F:/manifest-...../DICOM/FDG-PET-CT-Lesions/ F:/maniftest-..../NIFTI/FDG-PET-CT-Lesions/` should work

![联想截图_20240116101342](https://github.com/lab-midas/TCIA_processing/assets/125953252/72307f1c-3b91-4dd5-bd79-9199372c002e)
![联想截图_20240116101403](https://github.com/lab-midas/TCIA_processing/assets/125953252/e655a766-a912-4d06-acb2-c0881c8f5e8d)
Sorry, my screenshot is wrong, I tried the command you gave, and it still doesn't work, this is the file directory where I downloaded the data, I don't know if there is a problem with the file directory I entered

**Comment by thomaskuestner** [comment]
Do you have read/write access in these directories? 
For us this is all working and since you do not see any error message, I assume that there is nothing wrong with the code. Can you debug yourself through the code and see if it branches out of the code before creating any files?

**Comment by liangzw599** [comment]
OverflowError: Python integer -1024 out of bounds for uint16
**************************************************************
Why did I make this mistake？

**Comment by thomaskuestner** [comment]
@liangzw599 Please refer to the previous issue: https://github.com/lab-midas/TCIA_processing/issues/3
In short, you are working with an unsupported Python version that has package conflicts. Please use Python <= 3.10
